# Generated by Django 5.2 on 2025-07-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClimateDataPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("country", models.CharField(max_length=50)),
                ("region", models.CharField(blank=True, max_length=100)),
                (
                    "sea_level_rise",
                    models.FloatField(help_text="Projected sea level rise in meters"),
                ),
                (
                    "temperature_increase",
                    models.FloatField(
                        help_text="Average temperature increase in Celsius"
                    ),
                ),
                (
                    "erosion_risk",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                (
                    "flood_risk",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                ("data_source", models.CharField(blank=True, max_length=200)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Climate Data Point",
                "verbose_name_plural": "Climate Data Points",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ClimateRiskArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "risk_type",
                    models.CharField(
                        choices=[
                            ("flooding", "Flooding"),
                            ("erosion", "Coastal Erosion"),
                            ("heat", "Heat Stress"),
                            ("sea_level", "Sea Level Rise"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                ("center_latitude", models.FloatField()),
                ("center_longitude", models.FloatField()),
                (
                    "radius_km",
                    models.FloatField(help_text="Approximate radius in kilometers"),
                ),
                ("description", models.TextField()),
                ("impact_assessment", models.TextField(blank=True)),
                ("adaptation_measures", models.TextField(blank=True)),
                ("data_source", models.CharField(blank=True, max_length=200)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Climate Risk Area",
                "verbose_name_plural": "Climate Risk Areas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("date", models.DateField()),
                ("temperature_max", models.FloatField(blank=True, null=True)),
                ("temperature_min", models.FloatField(blank=True, null=True)),
                (
                    "precipitation",
                    models.FloatField(
                        blank=True, help_text="Precipitation in mm", null=True
                    ),
                ),
                (
                    "wind_speed",
                    models.FloatField(
                        blank=True, help_text="Wind speed in m/s", null=True
                    ),
                ),
                (
                    "humidity",
                    models.FloatField(
                        blank=True, help_text="Humidity percentage", null=True
                    ),
                ),
                ("is_forecast", models.BooleanField(default=False)),
                ("data_source", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Weather Data",
                "verbose_name_plural": "Weather Data",
                "ordering": ["-date"],
                "unique_together": {("location", "date", "is_forecast")},
            },
        ),
    ]
